### ISSUE TITLE
Wabbajack not detecting KSP

### ISSUE THREAD

**Issue by EarthDefenceForces** [LaughingHyena279/BoxOfRockets#5]
I ran into an issue of Wabbajack not detecting the KSP installation if multiple steam libraries are used.

Of course, this is not an issue of this mod list, but it may be nice to have this info here. 

To fix this issue, go to the steam library folder and edit the corresponding app manifest (appmanifest_220200.acf). Add the lines:
"BytesToDownload"	"0"  
"BytesDownloaded"	"0"  
"BytesToStage"		"0"  
"BytesStaged"		"0"

Again, thank you very much for this mod list!

**Comment by LaughingHyena279** [comment]
Since this is a WJ issue, I recommend reporting it on the WJ github so they can look into fixing it, if they haven't already!
